### ISSUE TITLE
SyntaxError with python2

### ISSUE THREAD

**Issue by khaeusler** [OCA/openupgradelib#159] opened 2019-07-18 16:24 UTC
Hello

i've tried to install the master version of openupgradelib in a docker container with odoo 10; i got this error.

```
sudo pip install git+https://github.com/OCA/openupgradelib.git
Downloading/unpacking git+https://github.com/OCA/openupgradelib.git
  Cloning https://github.com/OCA/openupgradelib.git to /tmp/pip-K4kIat-build
  Running setup.py (path:/tmp/pip-K4kIat-build/setup.py) egg_info for package from git+https://github.com/OCA/openupgradelib.git
    /tmp/pip-K4kIat-build/setup.py:12: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
    
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib/python2.7/dist-packages (from openupgradelib==2.0.0)
Requirement already satisfied (use --upgrade to upgrade): cssselect in /usr/local/lib/python2.7/dist-packages (from openupgradelib==2.0.0)
Installing collected packages: openupgradelib
  Running setup.py install for openupgradelib
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
      File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade_120.py", line 55
        *(_r("col%s-%s" % (t3, col), "col%s-%s" % (t4, col))
        ^
    SyntaxError: invalid syntax
    
  Could not find .egg-info directory in install record for openupgradelib==2.0.0 from git+https://github.com/OCA/openupgradelib.git
Successfully installed openupgradelib
Cleaning up...
```

**Comment by pedrobaeza** [comment] 2019-07-19 07:35
I'm doing the same without problem:
```
$ sudo pip install git+https://github.com/OCA/openupgradelib.git --upgrade
Collecting git+https://github.com/OCA/openupgradelib.git
  Cloning https://github.com/OCA/openupgradelib.git to /tmp/pip-2pEzke-build
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from openupgradelib==2.0.0)
Requirement already up-to-date: cssselect in /usr/lib/python2.7/dist-packages (from openupgradelib==2.0.0)
Installing collected packages: openupgradelib
  Running setup.py install for openupgradelib ... done
Successfully installed openupgradelib-2.0.0
```
Are you running this with Python 2.7?

**Comment by khaeusler** [comment] 2019-07-19 15:51
yes, with Python 2.7.9

could you test it with
```
sudo pip uninstall openupgradelib
sudo pip install git+https://github.com/OCA/openupgradelib.git

ls -la /usr/local/lib/python2.7/dist-packages/openupgradelib/
```

**Comment by khaeusler** [comment] 2019-07-19 16:00
on my local machine

```
khaeusler@W530:~
$ python --version
Python 2.7.15+
khaeusler@W530:~
$ cd /tmp/
khaeusler@W530:/tmp
$ git clone https://github.com/OCA/openupgradelib.git
Klone nach 'openupgradelib' ...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 1379 (delta 20), reused 39 (delta 20), pack-reused 1339
Empfange Objekte: 100% (1379/1379), 483.13 KiB | 1.60 MiB/s, Fertig.
Löse Unterschiede auf: 100% (817/817), Fertig.
khaeusler@W530:/tmp
$ python openupgradelib/openupgradelib/openupgrade_120.py 
  File "openupgradelib/openupgradelib/openupgrade_120.py", line 55
    *(_r("col%s-%s" % (t3, col), "col%s-%s" % (t4, col))
    ^
SyntaxError: invalid syntax
khaeusler@W530:/tmp
```

**Comment by pedrobaeza** [comment] 2019-07-19 17:04
Of course, you mustn't do it that way. That files is exclusive for Odoo 12.0. I have uninstall and installing again without problem, and check Travis that is working even with that warning:

https://travis-ci.org/OCA/openupgradelib/builds/559440147

**Comment by khaeusler** [comment] 2019-07-19 19:21
the current oca/openupgrade code vor v10 need not openuprgadelib in version 2.0.0 but the master version.
E.g. problems with the method merge_records and the method delete_records_safely_by_xml_id nonexists

How can i install the openupgradelib@master with pip?

this works, but is not nice …
```
cd /tmp/
git clone https://github.com/OCA/openupgradelib.git
cd openupgradelib/
unlink openupgradelib/openupgrade_120.py
sudo pip install .
```

**Comment by pedrobaeza** [comment] 2019-07-19 19:28
But as said, `sudo pip install git+https://github.com/OCA/openupgradelib.git` works for me. Look if you have something stricter in your system. I'm using Ubuntu 18.04.

**Comment by khaeusler** [comment] 2019-07-19 19:42
I see, my local machine has kubuntu 18.04 and it works, the docker container hat Debian 8.11 and it doesn't work …

**Comment by khaeusler** [comment] 2019-07-19 20:32
create a docker container with the image debian:jessie
```
apt update
apt-get install --no-install-recommends python-pip git python-lxml python-cssselect
pip install git+https://github.com/OCA/openupgradelib/ # ERROR
```

with debian:stretch (no problems)
```
apt update
apt-get install --no-install-recommends python-pip git python-setuptools
pip install git+https://github.com/OCA/openupgradelib/ # it works
```

**Comment by pedrobaeza** [comment] 2019-07-19 21:08
@Yajo can you help here?

**Comment by Yajo** [comment] 2019-07-22 09:30
The error is expected if you're pycompiling the folder, because indeed that's py3-only syntax. However, that file shouldn't need py2 compatibility because there's no situation where it should be executed under py2.

Consider that error a warning and ignore it.

The best solution would be to be able to remove that file in py2 installs. @sbidoul @lmignon could you help better here? You have deeper knowledge on pip stuff.

**Comment by pedrobaeza** [comment] 2019-10-11 18:16
Any clue here then?

**Comment by sbidoul** [comment] 2019-10-11 20:27
I'd recommend to create a branch for the py2 version and continue with pure
py3 on master.

Le ven. 11 oct. 2019 à 20:16, Pedro M. Baeza <notifications@github.com> a
écrit :

**Comment by pedrobaeza** [comment] 2019-10-11 21:11
Well, not the best option because both branches will require to evolve for the same features.

**Comment by Yajo** [comment] 2019-10-14 11:03
I have been trying to fix this using `setuptools.find_packages(exclude=[version_specific_packages])` but had no luck. Running `./setup.py bdist` always tries to pycompile all code and fails.

I guess you just have to ignore that error.

**Comment by sbidoul** [comment] 2019-10-14 11:11
> both branches will require to evolve for the same features

I don't think there is a simple solution. Either make the whole lib 2+3 compatible, or branch off for python 2 in maintenance mode and embrace python 3 for master.

**Comment by legalsylvain** [comment] 2019-11-22 17:27
I think also that we should consider to create a new branch that is only python 3 compatible, and let and a version of openupgradelib compatible for both versions, only for maintenance.

**Regarding Odoo version :** 
python 2 is required for migration from : 
- 7.0 : (End of official support : 2016)
- 8.0 : (End of official support : 2017)
- 9.0 : (End of official support : 2018)

**Regarding Python 2 support**
Python is officialy unsupported from end of 2019. (now)

I know that a lot of instances are running under version <= 9.0 (*), but I don't think that new features (functions, etc...) will be introduced now for migration from 9.0 version (or before). So we can choose a date (for exemple, end of 2019, _but it's just a proposal_) from witch openupgrade master is only V3 compatible.
Maybe a little more work to maintain both branches, but also it will be more easely to improve a lib without the double compatibility constraint.

my 2 cents.

@StefanRijnhart, other @OCA/openupgrade-maintainers : What are your point of view ? 

(*) I didn't finished at GRAP the migration from 8.0 to 12.0 but coming soon !

**Comment by pedrobaeza** [comment] 2019-11-22 17:51
@legalsylvain that's not practical, and there are improvements over existing methods that apply to all versions. Examples:

https://github.com/OCA/openupgradelib/pull/188
https://github.com/OCA/openupgradelib/pull/168

Doing what you say will imply to double the work for maintaining them.

**Comment by legalsylvain** [comment] 2019-11-22 17:56
#188 and #168 are improvements. Not bug fixes. So no imperious need to backport those improvement in the python2 branch.

But well, I don't understand your point of you. What is your proposal ?

- Break python2 compatibility in a later date ? 2021, 2022 ?
- Never break python2 compatibility ?

regards.

**Comment by pedrobaeza** [comment] 2019-11-22 18:06
We have made one of that improvement for a v6.1 being migrated to v12 that we have now (bounced from others), so it's important to have it everywhere.

My proposal is to be able to compile only the files required on P2 versions when deploying to pip. Remember that the problem is that the specific v12 file is trying to be compiled against P2, while that file shouldn't be part of that compilation.

**Comment by Yajo** [comment] 2019-11-26 10:41
> #188 and #168 are improvements. Not bug fixes. So no imperious need to backport those improvement in the python2 branch.

I actually did those improvements for migrating python2 codebases, so yes there was an imperious need :yum: 

I added some patches for v7/8 migration recently.



> My proposal is to be able to compile only the files required on P2 versions when deploying to pip. Remember that the problem is that the specific v12 file is trying to be compiled against P2, while that file shouldn't be part of that compilation.

That's a very sane option.

**Comment by AussieScorpio** [comment] 2023-03-12 07:51
I'm attempting to migrate from 9.0 to 10.0 and facing exactly this issue. I've spent the last 3 days trying to come up with an environment where I can run the migration, but getting nowhere. The documentation for OpenUpgrade doesn't make mention of any of this. How can I create a Python 2.7 environment with the pre-requisites for an OpenUpgrade migration?

**Comment by hbrunn** [comment] 2023-03-12 16:55
the same way you created your existing OpenERP environment + some old enough version of openupgradelib

**Comment by AussieScorpio** [comment] 2023-03-17 06:06
> the same way you created your existing OpenERP environment + some old enough version of openupgradelib

Tried this. Version 2.0.0 is the latest version that will install. But I then end up with an issue of an error in the migration of "object has no attribute 'delete_records_safely_by_xml_id'". It's suggested in this post that the problem is that my version of openupgradelib is too old; https://github.com/OCA/OpenUpgrade/issues/1788.
How can I get this working? Too new and it doesn't install, too old and it lacks the methods required for migration.

**Comment by hbrunn** [comment] 2023-03-17 07:00
I'd start with doing `git blame` to see where this was added, then you end up at

https://github.com/OCA/openupgradelib/commit/52c8a87b52dc6355df2ce30b72d4e32afab0efa7

so

`pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@52c8a87b52dc6355df2ce30b72d4e32afab0efa7`

should give you a version that has this function. Then you can walk up the commit history until you find the latest commit that still installs in py2 and that should be the version that works for v11.

Would be great if you come back with that commit, then we can add a tag for future people in your predicament. It would have been better of course if we'd had taken better care of the transition back then, but well, didn't happen and I personally have migrated off py2 long ago so, won't spend a lot of time on fixing this now.

**Comment by AussieScorpio** [comment] 2023-03-17 07:05
To be honest, I'm about ready to give up on OpenUpgrade as an option alltogether. There are just too many issues. Too many things don't work, and it's not properly documented. Given the time I've already invested, I could have been half way into building a custom SQL migration straight into Odoo 16. And I still don't know what pitfalls await going from 10 -> 11 -> 12 -> 13 -> 14 -> 15 -> 16. We just can't justify months of work for something that might work; if we're lucky.

**Comment by hbrunn** [comment] 2023-03-17 07:05
to be honest, that's totally up to you

**Comment by pedrobaeza** [comment] 2023-03-17 07:08
I'm migrating from v8 with the latest openupgradelib, and without doing anything special (just pip install), so it's something of your environment setup. This thread can continue in the discussion forum, as this is not an openupgradelib issue per se.

**Closed by pedrobaeza** 2023-03-17 07:08 UTC

**Comment by AussieScorpio** [comment] 2023-03-17 07:10
> I'm migrating from v8 with the latest openupgradelib, and without doing anything special (just pip install), so it's something of your environment setup. This thread can continue in the discussion forum, as this is not an openupgradelib issue per se.

I can't see how  that's possible when the latest openupgradelib does not run on Python 2.7.

**Comment by hbrunn** [comment] 2023-03-17 16:42
probably beating a dead horse, but the below seems to me that whatever you do, you do it wrong:


```
# docker run -ti python:2.7.18-stretch bash
root@5f047ec7c751:/# pip install openupgradelib
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting openupgradelib
  Downloading openupgradelib-3.4.1-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 5.5 MB/s 
Collecting cssselect
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting lxml
  Downloading lxml-4.9.2-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.7 MB)
     |████████████████████████████████| 5.7 MB 40.5 MB/s 
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python2.7/site-packages (from openupgradelib) (1.6.0)
Requirement already satisfied: contextlib2; python_version < "3" in /usr/local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->openupgradelib) (0.6.0.post1)
Requirement already satisfied: pathlib2; python_version < "3" in /usr/local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->openupgradelib) (2.3.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->openupgradelib) (1.2.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /usr/local/lib/python2.7/site-packages (from importlib-metadata; python_version < "3.8"->openupgradelib) (4.0.2)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from pathlib2; python_version < "3"->importlib-metadata; python_version < "3.8"->openupgradelib) (1.14.0)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from pathlib2; python_version < "3"->importlib-metadata; python_version < "3.8"->openupgradelib) (1.10.0)
Installing collected packages: cssselect, lxml, openupgradelib
Successfully installed cssselect-1.1.0 lxml-4.9.2 openupgradelib-3.4.1
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@5f047ec7c751:/# python
Python 2.7.18 (default, Apr 20 2020, 19:39:49) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import openupgradelib
>>>
```
